name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Run tests
        run: deno test

      - name: Build executable
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: deno run build

      - name: Upload to Cloudflare R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.POWERPCU_EXPORT_R2_RW_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.POWERPCU_EXPORT_R2_RW_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        uses: aws-actions/aws-cli@v2
        with:
          args: |
            s3 cp ./out/powerpcu_export.exe s3://$R2_BUCKET/powerpcu_export.exe \
            --endpoint-url $R2_ENDPOINT
