name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Run tests
        run: deno test -A

      - name: Build executable
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: deno run build

      - name: Upload to Cloudflare R2
        uses: magicwallet/r2-upload@main
        with:
          endpoint: ${{ secrets.R2_ENDPOINT }}
          access_key_id: ${{ secrets.POWERPCU_EXPORT_R2_RW_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.POWERPCU_EXPORT_R2_RW_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.R2_BUCKET }}
          file: ./out/powerpcu_export.exe
          destination: "powerpcu_export.exe"
